/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/travels/expenses/{expenseId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rejectExpense"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/expenses/{expenseId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["approveExpense"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllTravels"];
        put?: never;
        post: operations["createTravel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/{travelId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/{travelId}/itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItinerary"];
        put?: never;
        post: operations["addItinerary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/{travelId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExpenses"];
        put?: never;
        post: operations["addExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/{travelId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTravelDocuments"];
        put?: never;
        post: operations["uploadTravelDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/{travelId}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBookings"];
        put?: never;
        post: operations["addBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/expenses/{expenseId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExpenseDocs"];
        put?: never;
        post: operations["uploadExpenseDocs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/{travelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTravel"];
        put?: never;
        post?: never;
        delete: operations["deleteTravel"];
        options?: never;
        head?: never;
        patch: operations["updateTravel"];
        trace?: never;
    };
    "/travels/itinerary/{itineraryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateItinerary"];
        trace?: never;
    };
    "/travels/booking/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteBooking"];
        options?: never;
        head?: never;
        patch: operations["updateBooking"];
        trace?: never;
    };
    "/profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserTravels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyTravels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDescendingLayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/travels/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: Record<string, never>;
        };
        TravelMemberRequest: {
            member_ids?: string[];
        };
        TravelRequest: {
            title?: string;
            description?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            destination?: string;
            travelMemberIds?: components["schemas"]["TravelMemberRequest"];
        };
        ApiResponseTravelResponseSummary: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelResponseSummary"];
        };
        TravelMemberResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            member_id?: string;
            name?: string;
            role?: string;
            email?: string;
        };
        TravelResponseSummary: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            destination?: string;
            /** @enum {string} */
            status?: "PLANNED" | "ONGOING" | "COMPLETED" | "CANCELLED";
            createdByName?: string;
            travel_members?: components["schemas"]["TravelMemberResponse"][];
        };
        ApiResponseSetTravelMemberResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelMemberResponse"][];
        };
        TravelItineraryRequest: {
            title?: string;
            description?: string;
            /** Format: date-time */
            startDateTime?: string;
            /** Format: date-time */
            endDateTime?: string;
            location?: string;
        };
        ApiResponseTravelItineraryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelItineraryResponse"];
        };
        TravelItineraryResponse: {
            /** Format: uuid */
            itineraryId?: string;
            title?: string;
            description?: string;
            /** Format: date-time */
            startDateTime?: string;
            /** Format: date-time */
            endDateTime?: string;
            location?: string;
        };
        TravelExpenseRequest: {
            /** Format: uuid */
            paid_by?: string;
            /** @enum {string} */
            expense_type?: "TRANSPORTATION" | "ACCOMMODATION" | "MEALS" | "ENTERTAINMENT";
            title?: string;
            amount?: number;
            currency?: string;
            /** Format: date */
            expenseDate?: string;
        };
        ApiResponseTravelExpenseResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelExpenseResponse"];
        };
        TravelExpenseResponse: {
            /** Format: uuid */
            paid_by?: string;
            /** @enum {string} */
            expense_type?: "TRANSPORTATION" | "ACCOMMODATION" | "MEALS" | "ENTERTAINMENT";
            title?: string;
            description?: string;
            amount?: number;
            currency?: string;
            /** Format: date */
            expenseDate?: string;
            /** Format: uuid */
            approved_by?: string;
            /** Format: uuid */
            id?: string;
        };
        ApiResponseDocUploadResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["DocUploadResponse"];
        };
        DocUploadResponse: {
            uploadedDocs?: string[];
            failedDocs?: string[];
            errors?: string[];
        };
        TravelBookingRequest: {
            /** Format: uuid */
            travel_id?: string;
            /** @enum {string} */
            bookingType?: "FLIGHT" | "HOTEL" | "TRAIN" | "BUS" | "CAB" | "OTHER";
            provider_name?: string;
            booking_reference?: string;
            amount?: number;
            currency?: string;
            /** Format: date-time */
            start_dateTime?: string;
            /** Format: date-time */
            end_dateTime?: string;
        };
        ApiResponseTravelBookingResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelBookingResponse"];
        };
        TravelBookingResponse: {
            /** Format: uuid */
            booking_id?: string;
            /** Format: uuid */
            travel_id?: string;
            /** @enum {string} */
            bookingType?: "FLIGHT" | "HOTEL" | "TRAIN" | "BUS" | "CAB" | "OTHER";
            provider_name?: string;
            booking_reference?: string;
            amount?: number;
            currency?: string;
            /** Format: date-time */
            start_dateTime?: string;
            /** Format: date-time */
            end_dateTime?: string;
        };
        ProfileAdminRequestDTO: {
            /** Format: uuid */
            userId?: string;
            empNumber?: string;
            /** Format: uuid */
            departmentId?: string;
            /** Format: date */
            joinedDate?: string;
            phone?: string;
            bio?: string;
            location?: string;
        };
        ApiResponseProfileResponseDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProfileResponseDTO"];
        };
        ProfileResponseDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            empNumber?: string;
            phone?: string;
            bio?: string;
            location?: string;
            avatarUrl?: string;
            /** Format: date */
            joinedDate?: string;
            /** Format: uuid */
            departmentId?: string;
            departmentName?: string;
        };
        RegisterRequestDto: {
            first_name?: string;
            last_name?: string;
            email?: string;
            password?: string;
            confirm_password?: string;
            /** Format: uuid */
            role?: string;
            /** Format: uuid */
            reports_to?: string;
        };
        ApiResponseRegisterResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["RegisterResponseDto"];
        };
        RegisterResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            role?: string;
            reports_to?: string;
        };
        ApiResponseAuthResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AuthResponseDto"];
        };
        AuthResponseDto: {
            accessToken?: string;
            userDetailResponse?: components["schemas"]["UserDetailResponse"];
        };
        UserDetailResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            /** Format: date-time */
            last_login?: string;
            role?: string;
            /** Format: uuid */
            reports_to?: string;
            permission?: string[];
            is_active?: boolean;
        };
        ApiResponseString: {
            success?: boolean;
            message?: string;
            data?: string;
        };
        LoginRequestDto: {
            email?: string;
            password?: string;
        };
        TravelUpdateRequest: {
            title?: string;
            description?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            destination?: string;
        };
        ProfileSelfUpdateDTO: {
            phone?: string;
            bio?: string;
            location?: string;
        };
        ApiResponseUserDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserDetailResponse"];
        };
        ApiResponseListTravelResponseSummary: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelResponseSummary"][];
        };
        ApiResponseTravelResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelResponse"];
        };
        TravelDocResponse: {
            /** Format: uuid */
            id?: string;
            fileUrl?: string;
            /** Format: uuid */
            uploadedBy?: string;
            /** Format: date-time */
            uploadedAt?: string;
        };
        TravelResponse: {
            title?: string;
            description?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            destination?: string;
            /** @enum {string} */
            status?: "PLANNED" | "ONGOING" | "COMPLETED" | "CANCELLED";
            travelMembers?: components["schemas"]["TravelMemberResponse"][];
            itineraries?: components["schemas"]["TravelItineraryResponse"][];
            expenses?: components["schemas"]["TravelExpenseResponse"][];
            travel_bookings?: components["schemas"]["TravelBookingResponse"][];
            travelDocument?: components["schemas"]["TravelDocResponse"][];
            /** Format: uuid */
            created_by?: string;
            created_by_name?: string;
            /** Format: uuid */
            id?: string;
        };
        ApiResponseListTravelItineraryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelItineraryResponse"][];
        };
        ApiResponseListTravelExpenseResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelExpenseResponse"][];
        };
        ApiResponseListTravelDocument: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelDocument"][];
        };
        Comment: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            user?: components["schemas"]["User"];
            post?: components["schemas"]["Post"];
            content?: string;
        };
        Department: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            department_name?: string;
            department_code?: string;
            employees?: components["schemas"]["Profile"][];
            job_openings?: components["schemas"]["Job"][];
        };
        ExpenseDocument: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            uploadedBy?: components["schemas"]["User"];
            travelExpense?: components["schemas"]["TravelExpense"];
            doc_url?: string;
        };
        Game: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            name?: string;
            description?: string;
            operatingStartTime?: components["schemas"]["LocalTime"];
            operatingEndTime?: components["schemas"]["LocalTime"];
            /** Format: int32 */
            slotDurationMinutes?: number;
            /** Format: int32 */
            maxPlayers?: number;
            slots?: components["schemas"]["GameSlot"][];
            game_interests?: components["schemas"]["GameInterest"][];
            game_cycle?: components["schemas"]["GameBookingCycle"][];
        };
        GameBookingCycle: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            game?: components["schemas"]["Game"];
            /** Format: date-time */
            cycle_start?: string;
            /** Format: date-time */
            cycle_end?: string;
            cycle_slots?: components["schemas"]["GameSlot"][];
        };
        GameInterest: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            user?: components["schemas"]["User"];
            game?: components["schemas"]["Game"];
        };
        GameSlot: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            game?: components["schemas"]["Game"];
            /** Format: date */
            slotDate?: string;
            startTime?: components["schemas"]["LocalTime"];
            endTime?: components["schemas"]["LocalTime"];
            /** Format: int32 */
            maxPlayers?: number;
            game_cycle?: components["schemas"]["GameBookingCycle"];
            bookings?: components["schemas"]["SlotBooking"][];
        };
        Job: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            title?: string;
            description?: string;
            job_responsibilities?: string;
            required_qualification?: string;
            employment_type?: string;
            salary_range?: string;
            /** @enum {string} */
            status?: "OPEN" | "CLOSED";
            /** Format: date */
            application_deadline?: string;
            min_experience?: string;
            location?: string;
            default_reviewer?: components["schemas"]["User"];
            department?: components["schemas"]["Department"];
            created_by?: components["schemas"]["User"];
            job_referrals?: components["schemas"]["Referral"][];
            shares?: components["schemas"]["JobSharingRecord"][];
            is_active?: boolean;
        };
        JobSharingRecord: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Like: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            user?: components["schemas"]["User"];
            post?: components["schemas"]["Post"];
            like_state?: boolean;
        };
        LocalTime: {
            /** Format: int32 */
            hour?: number;
            /** Format: int32 */
            minute?: number;
            /** Format: int32 */
            second?: number;
            /** Format: int32 */
            nano?: number;
        };
        Notification: {
            /** Format: int64 */
            notificationId?: number;
            recipient?: components["schemas"]["User"];
            actor?: components["schemas"]["User"];
            /** @enum {string} */
            type?: "LIKE" | "COMMENT" | "SLOT_BOOKED" | "SLOT_CANCELLED" | "BIRTHDAY" | "WORK_ANNIVERSARY" | "SYSTEM";
            /** @enum {string} */
            entityType?: "POST" | "SLOT" | "BOOKING" | "TRAVEL" | "USER" | "JOB";
            /** Format: int64 */
            entityId?: number;
            title?: string;
            message?: string;
            /** Format: date-time */
            createdAt?: string;
            read?: boolean;
        };
        Permission: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            code?: string;
            name?: string;
            description?: string;
        };
        Post: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            postOwner?: components["schemas"]["User"];
            title?: string;
            content?: string;
            visibility_role?: components["schemas"]["Role"];
            media?: components["schemas"]["PostMedia"][];
            likes?: components["schemas"]["Like"][];
            comments?: components["schemas"]["Comment"][];
            is_active?: boolean;
        };
        PostMedia: {
            id?: string;
            post?: components["schemas"]["Post"];
            media_url?: string;
        };
        Profile: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            user?: components["schemas"]["User"];
            emp_number?: string;
            phone?: string;
            bio?: string;
            avatar_url?: string;
            /** Format: date */
            joined_date?: string;
            department?: components["schemas"]["Department"];
            location?: string;
        };
        Referral: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            referred_by?: components["schemas"]["User"];
            job?: components["schemas"]["Job"];
            name?: string;
            details?: string;
            doc_url?: string;
        };
        RefreshToken: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            tokenHash?: string;
            userMail?: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            revoked_at?: string;
            replaced_by_tokenHash?: string;
            reason_revoked?: string;
            user?: components["schemas"]["User"];
        };
        Role: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            name?: string;
            description?: string;
            users?: components["schemas"]["User"][];
            posts?: components["schemas"]["Post"][];
            rolePermissions?: components["schemas"]["RolePermission"][];
        };
        RolePermission: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            role?: components["schemas"]["Role"];
            permission?: components["schemas"]["Permission"];
        };
        SlotBooking: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SlotParticipant: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Travel: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            title?: string;
            description?: string;
            createdBy?: components["schemas"]["User"];
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            destination?: string;
            /** @enum {string} */
            status?: "PLANNED" | "ONGOING" | "COMPLETED" | "CANCELLED";
            members?: components["schemas"]["TravelMember"][];
            itineraries?: components["schemas"]["TravelItinerary"][];
            expenses?: components["schemas"]["TravelExpense"][];
            travel_bookings?: components["schemas"]["TravelBooking"][];
            travel_documents?: components["schemas"]["TravelDocument"][];
        };
        TravelBooking: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            travel?: components["schemas"]["Travel"];
            /** @enum {string} */
            bookingType?: "FLIGHT" | "HOTEL" | "TRAIN" | "BUS" | "CAB" | "OTHER";
            provider_name?: string;
            booking_reference?: string;
            amount?: number;
            currency?: string;
            /** Format: date-time */
            start_dateTime?: string;
            /** Format: date-time */
            end_dateTime?: string;
        };
        TravelDocument: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            uploadedBy?: components["schemas"]["User"];
            travel?: components["schemas"]["Travel"];
            doc_url?: string;
        };
        TravelExpense: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            travel?: components["schemas"]["Travel"];
            paid_by?: components["schemas"]["User"];
            /** @enum {string} */
            expense_type?: "TRANSPORTATION" | "ACCOMMODATION" | "MEALS" | "ENTERTAINMENT";
            title?: string;
            description?: string;
            amount?: number;
            currency?: string;
            /** Format: date */
            expenseDate?: string;
            /** Format: date-time */
            approved_at?: string;
            remark?: string;
            /** @enum {string} */
            status?: "DRAFT" | "SUBMITTED" | "APPROVED" | "REJECTED";
            createdBy?: components["schemas"]["User"];
            approved_by?: components["schemas"]["User"];
            expense_docs?: components["schemas"]["ExpenseDocument"][];
        };
        TravelItinerary: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            travel?: components["schemas"]["Travel"];
            title?: string;
            description?: string;
            /** Format: date-time */
            startDateTime?: string;
            /** Format: date-time */
            endDateTime?: string;
            location?: string;
        };
        TravelMember: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            travel?: components["schemas"]["Travel"];
            user?: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            first_name?: string;
            last_name?: string;
            email?: string;
            password_hash?: string;
            /** Format: date-time */
            last_login?: string;
            role?: components["schemas"]["Role"];
            reports_to?: components["schemas"]["User"];
            reports_to_me?: components["schemas"]["User"][];
            my_notifications?: components["schemas"]["Notification"][];
            sent_notifications?: components["schemas"]["Notification"][];
            profile?: components["schemas"]["Profile"];
            user_posts?: components["schemas"]["Post"][];
            my_likes?: components["schemas"]["Like"][];
            my_comments?: components["schemas"]["Comment"][];
            travel_created_by_me?: components["schemas"]["Travel"][];
            jobs_created_by_me?: components["schemas"]["Job"][];
            my_referrals?: components["schemas"]["Referral"][];
            my_participation?: components["schemas"]["SlotParticipant"][];
            my_travel?: components["schemas"]["TravelMember"][];
            my_travel_docs?: components["schemas"]["TravelDocument"][];
            my_expense_docs?: components["schemas"]["ExpenseDocument"][];
            game_interests?: components["schemas"]["GameInterest"][];
            my_created_expenses?: components["schemas"]["TravelExpense"][];
            my_travel_expenses?: components["schemas"]["TravelExpense"][];
            refresh_tokens?: components["schemas"]["RefreshToken"][];
            my_approved_expenses?: components["schemas"]["TravelExpense"][];
            my_shared_jobs?: components["schemas"]["JobSharingRecord"][];
            jobs_under_my_review?: components["schemas"]["Job"][];
            is_active?: boolean;
        };
        ApiResponseListTravelBookingResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelBookingResponse"][];
        };
        ApiResponseListExpenseDocument: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExpenseDocument"][];
        };
        ApiResponseListUserDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserDetailResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rejectExpense: {
        parameters: {
            query: {
                remark: string;
            };
            header?: never;
            path: {
                expenseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    approveExpense: {
        parameters: {
            query: {
                remark: string;
            };
            header?: never;
            path: {
                expenseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAllTravels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelResponseSummary"];
                };
            };
        };
    };
    createTravel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelResponseSummary"];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSetTravelMemberResponse"];
                };
            };
        };
    };
    getItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelItineraryResponse"];
                };
            };
        };
    };
    addItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelItineraryResponse"];
                };
            };
        };
    };
    getExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelExpenseResponse"];
                };
            };
        };
    };
    addExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelExpenseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelExpenseResponse"];
                };
            };
        };
    };
    getTravelDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelDocument"];
                };
            };
        };
    };
    uploadTravelDocument: {
        parameters: {
            query: {
                files: string[];
            };
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDocUploadResponse"];
                };
            };
        };
    };
    getBookings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelBookingResponse"];
                };
            };
        };
    };
    addBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelBookingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelBookingResponse"];
                };
            };
        };
    };
    getExpenseDocs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expenseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExpenseDocument"];
                };
            };
        };
    };
    uploadExpenseDocs: {
        parameters: {
            query: {
                files: string[];
            };
            header?: never;
            path: {
                expenseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDocUploadResponse"];
                };
            };
        };
    };
    createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileAdminRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileResponseDTO"];
                };
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRegisterResponseDto"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponseDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponseDto"];
                };
            };
        };
    };
    getTravel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelResponse"];
                };
            };
        };
    };
    deleteTravel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateTravel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                travelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    deleteBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelBookingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileResponseDTO"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileAdminRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileResponseDTO"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileResponseDTO"];
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSelfUpdateDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileResponseDTO"];
                };
            };
        };
    };
    getUserDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserDetailResponse"];
                };
            };
        };
    };
    getMyDetail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserDetailResponse"];
                };
            };
        };
    };
    getUserTravels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelResponseSummary"];
                };
            };
        };
    };
    getMyTravels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelResponseSummary"];
                };
            };
        };
    };
    getDescendingLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUserDetailResponse"];
                };
            };
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
