spring.application.name=hrms

spring.datasource.url=jdbc:sqlserver://localhost:63887;databaseName=HRMS;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=harshpatel2601
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

jwt.secret=kECkEqIeu0SnRsvxT3QLf4GdseO3Oux7fhdghfdhtrcnhrdhjgfcn

ImageStoreUrl=C:\HRMS Assignment

secretKey=kECkEqIeu0SnRsvxT3QLf4GdseO3Oux7fhdghfdhtrcnhrdhjgfcn

cloudinary.cloud_name=dn2qdr7q1
cloudinary.api_key=592938552513519
cloudinary.api_secret=4RuCeFOHIsG2dCfmURvTir1Tg94

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=7883febf84b251
spring.mail.password=3641e2198296f2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true